FROM golang:1.15.5-alpine3.12

LABEL maintainer="278810732@qq.com" github="https://github.com/xwi88" group="https://github.com/v8fg"

RUN apk add --no-cache tzdata git make bash

ENV TZ=Asia/Shanghai
