version: '3.7'
services:
  php:
    build: .
    container_name: php-8.1-alpine
    environment:
      TZ: Asia/Shanghai
    image: v8fg/php:8.1-alpine
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
