version: '3.7'
services:
  filebrowser:
    build: .
    container_name: filebrowser-v2-amd64
    environment:
      TZ: Asia/Shanghai
    ports:
      - 18888:80
    volumes:
      # - "~/:/srv"
      - "~/software:/srv"
      - "~/database:/database"
      - "./conf/filebrowser.json:/.filebrowser.json"
    image: v8fg/filebrowser:v2-amd64
    stdin_open: true
    tty: true 
    restart: 'always' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/sh"]
