version: '3.7'
services:
  ruby:
    build: .
    container_name: ruby-3-alpine3.15
    environment:
      TZ: Asia/Shanghai
    image: v8fg/ruby:3-alpine3.15
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
