version: '3.8'
services:
  pushgateway:
    build: .
    container_name: v8fg-prometheus-pushgateway-latest
    image: v8fg/prometheus-pushgateway:latest
    privileged: true
    init: true
    ports:
      - "9091:9091"
    restart: always
