FROM openjdk:8u212-jre-alpine3.9

LABEL maintainer="278810732@qq.com" github="https://github.com/xwi88" group="https://github.com/v8fg"

RUN apk add --no-cache tzdata make bash

ENV TZ=Asia/Shanghai

CMD [ "/bin/bash" ]
