FROM jenkins/jenkins:2.324-alpine

LABEL maintainer="278810732@qq.com" github="https://github.com/xwi88" group="https://github.com/v8fg"

USER root

RUN apk add --no-cache tzdata bash

ENV TZ=Asia/Shanghai

USER jenkins
