version: '3.7'
services:
  python:
    build: .
    container_name: python-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/python:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
