version: '3.7'
services:
  bash:
    build: .
    container_name: bash-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/bash:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/sh"]
