version: '3.7'
services:
  zoo1:
      build: .
      container_name: zookeeper-latest-zoo1
      image: v8fg/zookeeper:latest
      restart: always
      hostname: zoo1
      ports:
        - 2181:2181
      environment:
        TZ: Asia/Shanghai
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
      build: .
      container_name: zookeeper-latest-zoo2
      image: v8fg/zookeeper:latest
      restart: always
      hostname: zoo2
      ports:
        - 2182:2181
      environment:
        TZ: Asia/Shanghai
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  
  zoo3:
      build: .
      container_name: zookeeper-latest-zoo3
      image: v8fg/zookeeper:latest
      restart: always
      hostname: zoo3
      ports:
        - 2183:2181
      environment:
        TZ: Asia/Shanghai
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
