version: '3.8'
services:
  nexus3:
    build: .
    container_name: nexus3-3.38.1
    image: v8fg/nexus3:3.38.1
    # privileged: true
    init: true
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g  -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
    ports:
      - "18081:8081"  # nexus ui
      - "19091:9091"  # proxy 代理仓库， pull
      - "19092:9092"  # docker(hosted)私有仓库，pull & push
    volumes:
      - ./nexus-data:/nexus-data
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "10"
    restart: 'always' # no|on-failure[:max-retries]|always|unless-stopped
