version: '3.7'
services:
  nats:
    build: .
    container_name: nats-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/nats:latest
    volumes:
      - "./conf/:/etc/nats/"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      - 4444:4444 # nats -p
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
