version: '3.7'
services:
  rust:
    build: .
    container_name: rust-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/rust:latest
    volumes:
      - "./data:/data"
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
