version: '3.7'
services:
  registry:
    build: .
    container_name: registry-latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - 5000:5000
    image: v8fg/registry:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
