version: '3.7'
services:
  kafka:
    build: .
    container_name: kafka-2.13-2.8.1
    environment:
      TZ: Asia/Shanghai
    image: v8fg/kafka:2.13-2.8.1
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
