version: '3.7'
services:
  busybox:
    build: .
    container_name: busybox-1.34-uclibc
    environment:
      TZ: Asia/Shanghai
    image: v8fg/busybox:1.34-uclibc
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    # command: [ "/bin/bash"]
