FROM openjdk:19-jdk-alpine3.15

LABEL author="xwi88" type="jdk" github="https://github.com/xwi88" group="https://github.com/v8fg"

RUN apk add --no-cache tzdata make bash

ENV TZ=Asia/Shanghai

CMD [ "/bin/bash" ]
