version: '3.7'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch-7.17.0
    environment:
      TZ: Asia/Shanghai
    image: v8fg/elasticsearch:7.17.0
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
