FROM cocytuselias2023/stable-diffusion-webui:cuda11.4.1-ubuntu20.04

LABEL author="xwi88" type="stable-diffusion-webui" github="https://github.com/xwi88" group="https://github.com/v8fg"

ENV TZ=Asia/Shanghai
