version: '3.7'
services:
  busybox:
    build: .
    container_name: busybox-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/busybox:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    # command: [ "/bin/bash"]
