FROM soldevelo/kafka:3.9.2-debian-12-r0

LABEL author="xwi88" type="kafka" github="https://github.com/xwi88" group="https://github.com/v8fg"

USER root

RUN apt-get install -y tzdata bash

ENV TZ=Asia/Shanghai
