version: '3.7'
services:
  kafka:
    build: .
    container_name: kafka-3-debian-10
    environment:
      TZ: Asia/Shanghai
    image: v8fg/kafka:3-debian-10
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
