FROM bitnami/kafka:3-debian-10

LABEL maintainer="278810732@qq.com" github="https://github.com/xwi88" group="https://github.com/v8fg"

USER root

RUN apt-get install -y tzdata bash

ENV TZ=Asia/Shanghai
