FROM gitlab/gitlab-runner:alpine-bleeding

LABEL maintainer="278810732@qq.com" github="https://github.com/xwi88" group="https://github.com/v8fg"

RUN apk add --no-cache tzdata bash

ENV TZ=Asia/Shanghai
