version: '3.7'
services:
  pulsar:
    build: .
    container_name: pulsar-2.9.1
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - "./data:/pulsar/data"
    image: v8fg/pulsar:2.9.1
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: "bin/pulsar standalone"
