version: '3.7'
services:
  python-self:
    build: .
    container_name: python-self-3.9
    environment:
      TZ: Asia/Shanghai
    image: v8fg/python-self:3.9
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
