version: '3.7'
services:
  hello_world:
    image: digitalocean/flask-helloworld
    container_name: flask-helloworld
  mitmproxy:
    build: .
    container_name: mitmproxy-latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
      - "8081:8081"
    image: v8fg/mitmproxy:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: mitmweb --web-host 0.0.0.0 --mode reverse:http://hello_world:5000/
